from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class FeatureDefinition:
    name: str
    category: str
    data_level: str
    description: str


_FEATURE_ROWS = [
    ("log_return_1m", "return", "bar", "One-minute log close-to-close return."),
    ("open_close_return_1m", "return", "bar", "One-minute open-to-close return."),
    ("return_3m", "return", "bar", "Three-minute close-to-close return."),
    ("return_5m", "return", "bar", "Five-minute close-to-close return."),
    ("return_10m", "return", "bar", "Ten-minute close-to-close return."),
    ("return_15m", "return", "bar", "Fifteen-minute close-to-close return."),
    ("return_30m", "return", "bar", "Thirty-minute close-to-close return."),
    ("return_60m", "return", "bar", "Sixty-minute close-to-close return."),
    ("overnight_gap_pct", "gap", "bar", "Session open versus prior session close."),
    ("open_to_now_return", "return", "bar", "Current close versus session open."),
    ("sma_dist_5", "trend", "bar", "Close distance from 5-bar simple moving average."),
    ("sma_dist_20", "trend", "bar", "Close distance from 20-bar simple moving average."),
    ("ema_dist_9", "trend", "bar", "Close distance from 9-bar exponential moving average."),
    ("ema_9_minus_ema_21", "trend", "bar", "Fast minus slow EMA spread."),
    ("ema_slope_9", "trend", "bar", "Slope of the 9-bar EMA."),
    ("linear_reg_slope_20", "trend", "bar", "Twenty-bar linear regression slope."),
    ("linear_reg_angle_20", "trend", "bar", "Twenty-bar linear regression angle."),
    ("tsf_error_20", "trend", "bar", "Close distance from time-series forecast."),
    ("aroon_osc_14", "trend", "bar", "Fourteen-bar Aroon oscillator."),
    ("adx_14", "trend", "bar", "Fourteen-bar directional trend strength."),
    ("plus_di_minus_di_spread", "trend", "bar", "Positive DI minus negative DI."),
    ("macd_hist", "trend", "bar", "MACD histogram."),
    ("ppo", "trend", "bar", "Percentage price oscillator."),
    ("trix", "trend", "bar", "Triple-smoothed rate of change."),
    ("true_range", "volatility", "bar", "Current true range."),
    ("atr_14", "volatility", "bar", "Fourteen-bar average true range."),
    ("natr_14", "volatility", "bar", "Normalized average true range."),
    ("realized_vol_5m", "volatility", "bar", "Five-minute realized volatility."),
    ("realized_vol_15m", "volatility", "bar", "Fifteen-minute realized volatility."),
    ("realized_vol_30m", "volatility", "bar", "Thirty-minute realized volatility."),
    ("parkinson_vol_20", "volatility", "bar", "High-low volatility estimator."),
    ("garman_klass_vol_20", "volatility", "bar", "OHLC volatility estimator."),
    ("high_low_range_pct", "volatility", "bar", "Current high-low range over close."),
    ("range_zscore_tod", "volatility", "bar", "Range z-score normalized by time of day."),
    ("volatility_ratio_5_30", "volatility", "bar", "Short volatility divided by longer volatility."),
    ("atr_percentile_20d", "volatility", "bar", "ATR percentile over recent sessions."),
    ("rolling_high_dist_20", "breakout", "bar", "Close distance from rolling 20-bar high."),
    ("rolling_low_dist_20", "breakout", "bar", "Close distance from rolling 20-bar low."),
    ("donchian_position_20", "breakout", "bar", "Close position within 20-bar Donchian channel."),
    ("breakout_strength_20", "breakout", "bar", "Breakout distance beyond 20-bar range."),
    ("opening_range_high_dist", "opening_range", "bar", "Close distance from opening range high."),
    ("opening_range_low_dist", "opening_range", "bar", "Close distance from opening range low."),
    ("premarket_high_dist", "opening_range", "bar", "Close distance from premarket high."),
    ("premarket_low_dist", "opening_range", "bar", "Close distance from premarket low."),
    ("prior_day_high_dist", "level", "bar", "Close distance from prior session high."),
    ("prior_day_low_dist", "level", "bar", "Close distance from prior session low."),
    ("prior_close_dist", "level", "bar", "Close distance from prior session close."),
    ("session_high_low_position", "level", "bar", "Close percentile inside current session range."),
    ("close_zscore_20", "mean_reversion", "bar", "Twenty-bar close z-score."),
    ("return_zscore_20", "mean_reversion", "bar", "Twenty-bar return z-score."),
    ("bollinger_percent_b", "mean_reversion", "bar", "Close position inside Bollinger bands."),
    ("bollinger_bandwidth", "volatility", "bar", "Bollinger band width."),
    ("rsi_14", "oscillator", "bar", "Fourteen-bar relative strength index."),
    ("stoch_k_14", "oscillator", "bar", "Fourteen-bar stochastic percent K."),
    ("stoch_d_14", "oscillator", "bar", "Fourteen-bar stochastic percent D."),
    ("stoch_rsi", "oscillator", "bar", "Stochastic RSI."),
    ("williams_r_14", "oscillator", "bar", "Fourteen-bar Williams R."),
    ("cci_20", "oscillator", "bar", "Twenty-bar commodity channel index."),
    ("cmo_14", "oscillator", "bar", "Fourteen-bar Chande momentum oscillator."),
    ("rolling_return_autocorr_20", "return", "bar", "Twenty-bar return autocorrelation."),
    ("volume_1m", "volume", "bar", "One-minute traded volume."),
    ("log_volume", "volume", "bar", "Log transformed volume."),
    ("volume_zscore_tod", "volume", "bar", "Volume z-score normalized by time of day."),
    ("relative_volume_5m", "volume", "bar", "Five-minute volume versus recent baseline."),
    ("cumulative_volume_vs_expected", "volume", "bar", "Session volume versus expected volume curve."),
    ("volume_spike_ratio", "volume", "bar", "Current volume divided by recent average volume."),
    ("obv_slope_20", "volume", "bar", "Twenty-bar on-balance volume slope."),
    ("money_flow_index_14", "volume", "bar", "Fourteen-bar money flow index."),
    ("chaikin_ad_slope", "volume", "bar", "Chaikin accumulation-distribution slope."),
    ("chaikin_oscillator", "volume", "bar", "Chaikin oscillator."),
    ("vwap_dist", "vwap", "bar", "Close distance from session VWAP."),
    ("anchored_vwap_open_dist", "vwap", "bar", "Close distance from open-anchored VWAP."),
    ("vwap_slope_15m", "vwap", "bar", "Fifteen-minute VWAP slope."),
    ("price_cross_vwap_age", "vwap", "bar", "Minutes since last VWAP cross."),
    ("vwap_reclaim_flag", "vwap", "bar", "Close reclaimed VWAP after trading below it."),
    ("typical_price_vwap_dist", "vwap", "bar", "Typical price distance from VWAP."),
    ("hlc3_return_5m", "return", "bar", "Five-minute return of typical price."),
    ("weighted_close_return_5m", "return", "bar", "Five-minute weighted close return."),
    ("candle_body_pct", "candle", "bar", "Candle body divided by close."),
    ("upper_shadow_pct", "candle", "bar", "Upper wick divided by close."),
    ("lower_shadow_pct", "candle", "bar", "Lower wick divided by close."),
    ("body_to_range", "candle", "bar", "Candle body divided by high-low range."),
    ("close_position_in_bar", "candle", "bar", "Close percentile inside current bar range."),
    ("inside_bar_flag", "candle", "bar", "Current bar range inside prior bar range."),
    ("outside_bar_flag", "candle", "bar", "Current bar range outside prior bar range."),
    ("doji_score", "candle", "bar", "Small body relative to full bar range."),
    ("engulfing_flag", "candle", "bar", "Current body engulfs prior body."),
    ("hammer_score", "candle", "bar", "Long lower wick hammer score."),
    ("shooting_star_score", "candle", "bar", "Long upper wick reversal score."),
    ("heikin_ashi_trend", "candle", "bar", "Heikin-Ashi directional state."),
    ("minute_of_session_sin", "time", "calendar", "Sine transform of session minute."),
    ("minute_of_session_cos", "time", "calendar", "Cosine transform of session minute."),
    ("minutes_since_open", "time", "calendar", "Elapsed minutes since regular session open."),
    ("minutes_to_close", "time", "calendar", "Remaining minutes before flatten time."),
    ("session_bucket", "time", "calendar", "Discrete open, midday, afternoon, close bucket."),
    ("day_of_week", "time", "calendar", "Day-of-week seasonality."),
    ("month_turn_flag", "time", "calendar", "Start or end of month flag."),
    ("fomc_day_flag", "event", "calendar", "Federal Reserve announcement day flag."),
    ("cpi_nfp_day_flag", "event", "calendar", "Inflation or payroll announcement day flag."),
    ("macro_event_window_flag", "event", "calendar", "Pre/post scheduled macro event window flag."),
    ("es_nq_spread_return", "cross_asset", "external_bar", "NQ return minus ES return."),
    ("nq_rty_relative_strength", "cross_asset", "external_bar", "NQ return versus RTY return."),
    ("vix_return_5m", "cross_asset", "external_bar", "Five-minute VIX move."),
    ("dxy_return_5m", "cross_asset", "external_bar", "Five-minute dollar index move."),
    ("ten_year_yield_change", "cross_asset", "external_bar", "Short-horizon Treasury yield change."),
    ("tick_rule_buy_volume_ratio", "order_flow", "tick", "Tick-rule buy volume divided by total volume."),
    ("signed_volume_imbalance", "order_flow", "tick", "Signed buy minus sell volume imbalance."),
    ("up_down_volume_delta", "order_flow", "tick", "Up-tick volume minus down-tick volume."),
    ("cumulative_delta", "order_flow", "tick", "Intraday cumulative signed volume delta."),
    ("vpin_proxy", "order_flow", "tick", "Volume-synchronized imbalance proxy."),
    ("bid_ask_spread", "microstructure", "quote", "Best bid-ask spread."),
    ("order_book_imbalance_l1", "microstructure", "quote", "Level-one bid size versus ask size imbalance."),
]

FEATURE_CATALOG = tuple(FeatureDefinition(*row) for row in _FEATURE_ROWS)


def feature_catalog_by_name() -> dict[str, FeatureDefinition]:
    return {feature.name: feature for feature in FEATURE_CATALOG}


def features_for_data_levels(data_levels: set[str]) -> tuple[FeatureDefinition, ...]:
    return tuple(feature for feature in FEATURE_CATALOG if feature.data_level in data_levels)
