from __future__ import annotations

import copy
import json
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from .strategy import StrategySpec, parse_strategy_spec
from .variants import stable_hash


TRAIN_VALIDATION_ONLY_KEYS = {"fold", "train_metrics", "validation_metrics"}


@dataclass(frozen=True)
class LLMStrategyProposal:
    model: str
    prompt: str
    response: str
    prompt_hash: str
    response_hash: str
    strategy: StrategySpec

    def audit_record(self) -> dict[str, Any]:
        return {
            "created_at": datetime.now(UTC).isoformat(),
            "model": self.model,
            "prompt_hash": self.prompt_hash,
            "response_hash": self.response_hash,
            "prompt": self.prompt,
            "response": self.response,
            "strategy_name": self.strategy.name,
            "strategy_spec_hash": stable_hash(self.strategy.raw),
        }


def build_strategy_prompt(
    seed_spec: StrategySpec,
    feedback: list[dict[str, Any]] | None = None,
    max_candidates: int = 1,
) -> str:
    payload = {
        "task": "Generate bounded Strategy Spec v0 candidates for deterministic local backtesting.",
        "constraints": [
            "Return JSON only.",
            "Do not generate executable code.",
            "Do not use martingale, loss doubling, infinite DCA, or unbounded grid logic.",
            "Every candidate must keep hard stop loss, take profit, max holding time, and max position.",
            "Use bounded parameter ranges only.",
            "Optimize from train and validation feedback only; test and final holdout details are hidden.",
        ],
        "max_candidates": max_candidates,
        "seed_strategy": seed_spec.raw,
        "train_validation_feedback": feedback or [],
    }
    return json.dumps(payload, indent=2, sort_keys=True, default=str)


def train_validation_feedback(results: list[Any]) -> list[dict[str, Any]]:
    feedback = []
    for result in results:
        fold_feedback = [
            {key: value for key, value in fold.items() if key in TRAIN_VALIDATION_ONLY_KEYS}
            for fold in result.fold_results
        ]
        feedback.append(
            {
                "experiment_id": result.experiment_id,
                "strategy_name": result.strategy_name,
                "strategy_spec_hash": result.strategy_spec_hash,
                "variant_parameters": result.variant_parameters,
                "folds": fold_feedback,
            }
        )
    return feedback


class DeterministicLocalLLM:
    def __init__(self, model: str = "local-deterministic-template") -> None:
        self.model = model

    def propose(self, seed_spec: StrategySpec, feedback: list[dict[str, Any]] | None = None) -> LLMStrategyProposal:
        prompt = build_strategy_prompt(seed_spec, feedback=feedback)
        raw = self._mutate_seed(seed_spec.raw)
        response = json.dumps({"strategy_spec": raw}, indent=2, sort_keys=True)
        strategy = parse_strategy_spec(raw)
        return LLMStrategyProposal(
            model=self.model,
            prompt=prompt,
            response=response,
            prompt_hash=stable_hash(prompt),
            response_hash=stable_hash(response),
            strategy=strategy,
        )

    def _mutate_seed(self, raw_seed: dict[str, Any]) -> dict[str, Any]:
        raw = copy.deepcopy(raw_seed)
        raw["name"] = f"{raw['name']}_llm_proposal_0000"
        raw["market_hypothesis"] = (
            f"{raw['market_hypothesis']} Candidate is generated by the local deterministic "
            "LLM adapter for audit-safe strategy search."
        )
        parameters = raw.setdefault("parameters", {})
        if "opening_range_minutes" in parameters:
            parameters["opening_range_minutes"] = {"values": [5, 15, 30]}
        return raw


def parse_llm_response(response: str) -> StrategySpec:
    try:
        payload = json.loads(response)
    except json.JSONDecodeError as exc:
        raise ValueError("LLM response must be JSON") from exc
    if not isinstance(payload, dict) or not isinstance(payload.get("strategy_spec"), dict):
        raise ValueError("LLM response must contain a strategy_spec object")
    return parse_strategy_spec(payload["strategy_spec"])


def append_audit_log(path: Path, record: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(record, sort_keys=True, default=str) + "\n")
